# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow, QGraphicsView, QGraphicsScene, QVBoxLayout, QWidget
import pyqtgraph as pg
import numpy as np

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(70, 40, 631, 301))
        self.graphicsView.setObjectName("graphicsView")

        self.scene = QGraphicsScene()
        self.graphicsView.setScene(self.scene)

        # 创建一个 Pyqtgraph 组件
        self.plot_widget = pg.PlotWidget()
        self.plot_widget.setBackground('w')  # 设置背景为白色
        self.plot_widget.setMouseEnabled(x=False,y=False)

        # 在 Pyqtgraph 组件中绘制折线图
        # x = [0,1,2,3,4,5,6,7,8,]
        # y = [1,2,3,4,5,6,7,8,9]
        # bj1=pg.BarGraphItem(x=x,height=y,width=0.3,brush='r')
        # self.plot_widget.addItem(bj1)
        # self.plot_widget.resize(600,300)
        # self.plot_widget.setXRange(0,10)
        # self.plot_widget.setYRange(0,10)
        # # self.plot_widget.plot(x, y, pen=pg.mkPen(color='b', width=2))  # 绘制蓝色的折线图
        #
        #
        # # 将 Pyqtgraph 组件添加到 QGraphicsScene 中
        # self.scene.addWidget(self.plot_widget)
        # # 将 QGraphicsView 添加到主窗口中
        # layout = QVBoxLayout()
        # layout.addWidget(self.graphicsView)






        self.start_but = QtWidgets.QPushButton(self.centralwidget)
        self.start_but.setGeometry(QtCore.QRect(170, 410, 93, 28))
        self.start_but.setObjectName("start_but")

        self.stop_but = QtWidgets.QPushButton(self.centralwidget)
        self.stop_but.setGeometry(QtCore.QRect(460, 410, 93, 28))
        self.stop_but.setObjectName("stop_but")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.start_but.setText(_translate("MainWindow", "开始"))
        self.stop_but.setText(_translate("MainWindow", "暂停"))
